---
- hosts: hosts
  become: true
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Set timezone
      timezone:
        name: Asia/Dubai

    - name: Yum update
      yum:
        update_cache: yes
        name: '*'
        state: latest
        
    - name: Install usefull packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - epel-release
          - vim
          - nano
          - curl
          - wget
          - tcpdump
          - git
          - net-tools
          - bash-completion
          - openssl-devel
          - httpd-tools

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Stop and disable firewalld.
      service:
        name: firewalld
        state: stopped
        enabled: False
