---
- hosts: lbs
  become: true
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Install nginx mod stream
      yum:
        name: nginx-mod-stream
        state: present


    - name: Copy the NGINX config file
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        backup: yes

    - name: Start nginx
      systemd:
        name: nginx.service
        state: started
        enabled: yes

    - name: Restart nginx
      systemd:
        name: nginx.service
        state: restarted
...
